[Service]
Environment="NO_AT_BRIDGE=1"
Environment="UAV_SCENE_MODE=day"
Environment="UAV_LAYER_MODE=high"
Environment="UAV_RKNN_MODEL=/home/Tronlong/rknn_model_zoo/examples/yolov5/model/yolov5s_day_20260626.rknn"
Environment="UAV_YOLO_CONF=0.40"
Environment="UAV_CAPTURE_W=2560"
Environment="UAV_CAPTURE_H=1440"
Environment="UAV_DIFF_W=1920"
Environment="UAV_DIFF_H=1080"
Environment="UAV_PROCESS_EVERY_N_FRAMES=3"
Environment="UAV_DIRECT_FULL_FRAME_INFERENCE=0"
Environment="UAV_MOTION_ZOOM_CROP_SIZE=0"
Environment="UAV_MOTION_ZOOM_MAX_ROIS=0"
Environment="UAV_MOTION_ZOOM_ONLY=0"
Environment="UAV_TRACK_ZOOM_CROP_SIZE=0"
Environment="UAV_TRACK_SEARCH_ROIS=0"
Environment="UAV_HOVER_HOLD=1"
Environment="UAV_FULLFRAME_SEARCH_FALLBACK=0"
Environment="UAV_FULLFRAME_FALLBACK_ONLY=0"
Environment="UAV_EDGE_REGION_LAYER=1"
Environment="UAV_EDGE_REGION_SUPPRESS_LOW=1"
Environment="UAV_EDGE_REGION_FILL_BELOW=1"
Environment="UAV_EDGE_REGION_FILL_PAD_PX=12"
Environment="UAV_EDGE_REGION_UPDATE_FRAMES=30"
Environment="UAV_EDGE_REGION_CANNY_LOW=40"
Environment="UAV_EDGE_REGION_CANNY_HIGH=120"
Environment="UAV_EDGE_REGION_DENSITY_THRESH=0.045"
Environment="UAV_EDGE_REGION_MIN_AREA=700"
Environment="UAV_EDGE_REGION_KEEP_Y_RATIO=0.18"
Environment="UAV_EDGE_REGION_CLOSE_SIZE=9"
Environment="UAV_EDGE_REGION_DILATE_SIZE=21"
Environment="UAV_AUTO_CAM_LAYER=0"
Environment="UAV_SHOW_WINDOWS=0"
Environment="UAV_DRAW_INTERMEDIATE_BOXES=1"
Environment="UAV_MAX_DRAW_BOXES=300"
Environment="UAV_NIGHT_STATIC_POINT_SUPPRESS=0"
Environment="UAV_VIDEO_TARGET_IP=192.168.0.200"
Environment="UAV_VIDEO_BASE_PORT=9999"
Environment="UAV_VIDEO_STREAM_CAMS="
Environment="UAV_VIDEO_STREAM_W=640"
Environment="UAV_VIDEO_STREAM_H=480"
Environment="UAV_VIDEO_SEND_EVERY_N_FRAMES=1"
Environment="UAV_VIDEO_JPEG_QUALITY=25"
Environment="UAV_EDGE_REGION_DRAW_MASK=1"
Environment="UAV_EDGE_REGION_DRAW_ALPHA=0.30"
