[Service]
Environment="UAV_SCENE_MODE=night"
Environment="UAV_RKNN_MODEL=/home/Tronlong/rknn_model_zoo/examples/yolov5/model/yolov5s_night_latest.rknn"
Environment="UAV_CAPTURE_W=640"
Environment="UAV_CAPTURE_H=480"
Environment="UAV_DIFF_W=640"
Environment="UAV_DIFF_H=480"
Environment="UAV_PROCESS_EVERY_N_FRAMES=2"
Environment="UAV_DIRECT_FULL_FRAME_INFERENCE=0"
Environment="UAV_MOTION_ZOOM_CROP_SIZE=160"
Environment="UAV_MOTION_ZOOM_MAX_ROIS=1"
Environment="UAV_MOTION_ZOOM_ONLY=1"
Environment="UAV_TRACK_ZOOM_CROP_SIZE=0"
Environment="UAV_TRACK_SEARCH_ROIS=0"
Environment="UAV_HOVER_HOLD=0"
Environment="UAV_FULLFRAME_SEARCH_FALLBACK=0"
Environment="UAV_FULLFRAME_FALLBACK_ONLY=0"
