[Service]
Environment="UAV_VIDEO_TARGET_IP=192.168.0.200"
Environment="UAV_VIDEO_BASE_PORT=9999"
Environment="UAV_VIDEO_SEND_EVERY_N_FRAMES=3"
Environment="UAV_VIDEO_STREAM_W=320"
Environment="UAV_VIDEO_STREAM_H=180"
Environment="UAV_VIDEO_JPEG_QUALITY=35"
Environment="UAV_VIDEO_STREAM_CAMS="
Environment="UAV_DRAW_INTERMEDIATE_BOXES=0"
Environment="UAV_SHOW_WINDOWS=0"
Environment="DISPLAY=:0"
Environment="XAUTHORITY=/home/Tronlong/.Xauthority"
